{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finovabank.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "finovabank.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  - port: {{ $serviceConfig.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "finovabank.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
{{- end }}
